on:
  push:
    branches:
      - master
      
name: Build My App

jobs:
  build:
    name: Build And Release new apk
    runs-on: ubuntu-latest
    steps:
      - uses: action/checkout@v4
      - uses: action/setup-java@v2
        with:
          distribution: 'zulu'
          java-version: 11


      - uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
      - run: flutter pub get
      - run: flutter build apk --release --split-per-abi

      - name: Push to Releases
        uses: ncipollo/releases-action@v1
        with:
          artifacts: "build/app/outputs/apk/release/*"
          tag: v0.0.1
          token: ${{ secrets.TOKENMUSIC }}

